pipeline {
    agent any
    
    environment {
        mongoDB = 'mongoDB link'
    } 
    
    stages {
        stage('Pull code') {
            steps {
                checkout scm
            }
        }
        stage('Download dependency') {
            steps {
                dir("sdte-tnku"){
                    dir("backend"){
                        sh 'npm install'   
                    }   
                }
            }
        }
        stage("Run unit test"){
            steps {
                dir("sdte-tnku"){
                    dir("backend"){
                        sh 'npm run test'   
                    }
                }
            }
        }
        stage("Create unit test report"){
            steps {
                publishHTML([
                    allowMissing: false, 
                    alwaysLinkToLastBuild: false, 
                    keepAll: false, 
                    reportDir: './sdte-tnku/backend/mochawesome-report', 
                    reportFiles: 'mochawesome.html', 
                    reportName: 'Unit test report', 
                    reportTitles: ''
                ])
            }
        }
        stage("Deploy"){
            steps {
                echo "Waiting for vercel to deploy"
            }
        }
        stage("Notification"){
            steps {
                echo 'Waiting for email notification'
            }
        }
    }
}
