pipeline {
    agent any
    
    environment {
        mongoDB = 'mongoDB link'
    } 
    
    stages {
        stage('Pull code') {
            steps {
                checkout scm
            }
        }
        stage('Download dependency') {
            steps {
                dir("sdte-tnku"){
                    dir("backend"){
                        sh 'npm install'   
                    }   
                }
            }
        }
        stage("Run unit test"){
            steps {
                dir("sdte-tnku"){
                    dir("backend"){
                        sh 'npm run test'   
                    }
                }
            }
        }
        stage("Create unit test report"){
            steps {
                publishHTML([
                    allowMissing: false, 
                    alwaysLinkToLastBuild: false, 
                    keepAll: false, 
                    reportDir: './sdte-tnku/backend/mochawesome-report', 
                    reportFiles: 'mochawesome.html', 
                    reportName: 'Unit test report', 
                    reportTitles: ''
                ])
            }
        }
        stage("Create coverage test"){
            steps {
                dir("sdte-tnku"){
                    dir("backend"){
                        sh 'npm run test:coverage'   
                    }
                }
            }
        }
        stage("Create coverage report"){
            steps {
                publishHTML([
                    allowMissing: false, 
                    alwaysLinkToLastBuild: false, 
                    keepAll: false, 
                    reportDir: './sdte-tnku/backend/coverage', 
                    reportFiles: 'index.html', 
                    reportName: 'Coverage report', 
                    reportTitles: ''
                ])
            }
        }
        stage("Deploy"){
            steps {
                script{
                    def remote = [:]
                    remote.name = "root"
                    remote.host = '159.223.45.216'
                    remote.user = 'root'
                    remote.password = 'xitgmLwmp12q'
                    remote.allowAnyHosts = true
                    sshCommand remote: remote, command: "git clone https://github.com/BurnRadish/SW-Development_Group6_Project.git"
                    sshCommand remote: remote, command: "docker-compose -f SW-Development_Group6_Project/sdte-tnku/Docker-compose-build.yml build backend"
                    sshCommand remote: remote, command: "docker run -d -e PORT=2077 -p 2077:2077 --name team-6-backend it62070180/team-6-backend:1.0.0"
                    sshCommand remote: remote, command: "rm -r SW-Development_Group6_Project"
                }
            }
        }
        stage("Notification"){
            steps {
                echo 'Waiting for email notification'
            }
        }
    }
}
