pipeline {
    agent any
    
    environment {
         VUE_API_KEY = "API TAT KEY"
        
    }
    
    stages {
        stage('Pull code') {
            steps {
                git branch: 'frontend', url: 'https://github.com/BurnRadish/SW-Development_Group6_Project.git'
            }
        }
        stage('Download dependency') {
            steps {
                dir("sdte-tnku"){
                    dir("frontend"){
                        sh 'npm install'   
                    }   
                }
            }
        }
        stage('create cypress.env.json'){
            steps{
                echo 'create cypress.env.json'
            }
        }
        stage('add token cypress.env.json'){
            steps{
                echo 'add token in cypress.env.json'
            }
        }
        stage("Run Unit Test & Create Unit Test Report"){
            steps {
                dir("sdte-tnku"){
                    dir("frontend"){
                        sh "npm run test:unit-report"   
                    }
                }
            }
        }
        stage("Create Unit Test Code Coverage Report"){
            steps {
                publishHTML([
                    allowMissing: false, 
                    alwaysLinkToLastBuild: false, 
                    keepAll: false, 
                    reportDir: './sdte-tnku/frontend/coverage', 
                    reportFiles: 'index.html', 
                    reportName: 'Unit Test Code Coverage report', 
                    reportTitles: ''
                ])
            }
        }
        stage('Component Test & Create Component Test Report') {
            steps {
                dir("sdte-tnku"){
                    dir("frontend"){
                        sh 'npm install cypress'
                        sh 'npm run test:component-report'
                    }
                }
            }
        }
        stage("Create Component Test Coverage Report"){
            steps {
                publishHTML([
                    allowMissing: false, 
                    alwaysLinkToLastBuild: false, 
                    keepAll: false, 
                    reportDir: './sdte-tnku/frontend/mochawesome-report', 
                    reportFiles: 'index.html', 
                    reportName: 'Component Test Code Coverage report', 
                    reportTitles: ''
                ])
            }
        }
        stage('Deploy system') {
            steps {
                echo 'Deploy system with vercel'
            }
        }
        stage('Notification') {
            steps {
                echo 'Waiting for notification via vercel'
            }
        }
    }
}
