pipeline {
    agent any
    
    environment {
         VUE_API_KEY = "API TAT KEY"
        
    }
    
    stages {
        stage('Pull code') {
            steps {
                checkout scm
            }
        }
        stage('Download dependency') {
            steps {
                dir("sdte-tnku"){
                    dir("frontend"){
                        sh 'npm install'   
                    }   
                }
            }
        }
        stage('create cypress.env.json'){
            steps{
                echo 'create cypress.env.json'
            }
        }
        stage('add token cypress.env.json'){
            steps{
                echo 'add token in cypress.env.json'
            }
        }
        stage("Run Unit Test & Create Unit Test Report"){
            steps {
                dir("sdte-tnku"){
                    dir("frontend"){
                        sh "npm run test:unit-report"
                    }
                }
            }
        }
        stage("Create Unit Test Code Coverage Report"){
            steps {
                clover(cloverReportDir: 'stde-tnku/frontend/coverage', cloverReportFileName: 'clover.xml',
                healthyTarget: [methodCoverage: 70, conditionalCoverage: 80, statementCoverage: 80],
                unhealthyTarget: [methodCoverage: 0, conditionalCoverage: 0, statementCoverage: 0],
                failingTarget: [methodCoverage: 0, conditionalCoverage: 0, statementCoverage: 0])
                publishHTML([
                    allowMissing: false, 
                    alwaysLinkToLastBuild: false, 
                    keepAll: false, 
                    reportDir: 'sdte-tnku/frontend/coverage/lcov-report', 
                    reportFiles: 'index.html', 
                    reportName: 'Unit Test Code Coverage report',
                ])
            }
        }
        stage('Component Test & Create Component Test Report') {
            steps {
                dir("sdte-tnku"){
                    dir("frontend"){
                        sh 'npm install cypress'
                        sh 'npm run test:component-report'
                    }
                }
            }
        }
        stage("Create Component Test Coverage Report"){
            steps {
                publishHTML([
                    allowMissing: false, 
                    alwaysLinkToLastBuild: false, 
                    keepAll: false, 
                    reportDir: './sdte-tnku/frontend/cypress/reports/mochareports/', 
                    reportFiles: 'report.html', 
                    reportName: 'Component Test Code Coverage report', 
                    reportTitles: ''
                ])
            }
        }
        stage('Deploy system') {
            steps {
                echo 'Deploy system with vercel'
            }
        }
        stage('Notification') {
            steps {
                echo 'Waiting for notification via vercel'
            }
        }
    }
}
