pipeline {
    agent any
    
    environment {
         VUE_API_KEY = "API TAT KEY"
        
    }
    
    stages {
        stage('Pull code') {
            steps {
                git branch: 'frontend', url: 'https://github.com/BurnRadish/SW-Development_Group6_Project.git'
            }
        }
        stage('Download dependency') {
            steps {
                dir("sdte-tnku"){
                    dir("frontend"){
                        sh 'npm install'   
                    }   
                }
            }
        }
        stage('create cypress.env.json'){
            steps{
                echo 'create cypress.env.json'
            }
        }
        stage('add token cypress.env.json'){
            steps{
                echo 'add token in cypress.env.json'
            }
        }
        stage('Unit Test'){
            steps {
                dir("sdte-tnku"){
                    dir("frontend"){
                        sh "npm run test:unit"   
                    }
                }
            }
        }
        stage('...') {
            steps {
                clover(cloverReportDir: 'sdte-tnku/frontend/clover', cloverReportFileName: 'clover.xml',
                  // optional, default is: method=70, conditional=80, statement=80
                  healthyTarget: [methodCoverage: 70, conditionalCoverage: 80, statementCoverage: 80],
                  // optional, default is none
                  unhealthyTarget: [methodCoverage: 50, conditionalCoverage: 50, statementCoverage: 50],
                  // optional, default is none
                  failingTarget: [methodCoverage: 0, conditionalCoverage: 0, statementCoverage: 0]
                )
            }
        }
        stage('Component Test และ E2E Test') {
            steps {
                dir("sdte-tnku"){
                    dir("frontend"){
                        sh 'npm install cypress'
                        sh 'npx cypress run --spec "cypress/integration/result.spec.js"'
                    }
                }
            }
        }
        stage('Deploy system') {
            steps {
                echo 'Deploy system with vercel'
            }
        }
        stage('Notification') {
            steps {
                echo 'Waiting for notification via vercel'
            }
        }
    }
}
